spring.application.name=springbootfilebulk
server.servlet.context-path=/springbootfilebulk
server.port=9090



#MongoDB
# The connection string (database name is at the end)
spring.data.mongodb.uri=mongodb://localhost:27017/product_db

#To see loggers in consol
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG



# To expose only specific endpoints (recommended)
#management.endpoints.web.exposure.include=health,info,metrics,env,beans,trace

# OR to expose ALL endpoints (use only in development)
management.endpoints.web.exposure.include=*
