spring.application.name=springbootfilebulk
server.servlet.context-path=/springbootfilebulk
server.port=9090
spring.profiles.active=uat
#
#
##MongoDB
#spring.data.mongodb.uri=mongodb://localhost:27017/product_db
#spring.batch.job.enabled=false
#
## Configure datasource URL, username, and password
##Inmemory DB
###spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#
##file storage
##we are storing tem data in local system in below path
##spring.datasource.url=jdbc:h2:file:C:/Users/bhard/kollu/workspace/h2db/data/testdb
###spring.datasource.driverClassName=org.h2.Driver
###spring.datasource.username=sa
###spring.datasource.password=
#
## Required for Batch 5+ metadata
## Enable the H2 console for web access
###spring.h2.console.enabled=true
## Set the H2 console access path
###spring.h2.console.path=/h2-console
## 1. Tell Spring Batch to create the necessary tables in H2 automatically
##spring.batch.jdbc.initialize-schema=always
#
##We need to update below one while using MongoDB
#spring.batch.jdbc.initialize-schema=never
#
#spring.main.allow-bean-definition-overriding=true
## 2. Disable JPA/Hibernate auto-configuration 
## (Since you are using MongoDB, you don't need Hibernate trying to scan for entities)
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#
##To see loggers in consol
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#
#
## To expose only specific endpoints (recommended)
##management.endpoints.web.exposure.include=health,info,metrics,env,beans,trace
#
## OR to expose ALL endpoints (use only in development)
#management.endpoints.web.exposure.include=*
#
##Redies Cache - i am handling in config file
##spring.data.redis.host=localhost
##spring.data.redis.port=6379
### Optional: Set global TTL (Time-To-Live) for cache entries
##spring.cache.type=redis
##spring.cache.redis.time-to-live=600000
#
##spring.jackson.deserialization.fail-on-unknown-properties=false
