#MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/product_db
spring.batch.job.enabled=false

#We need to update below one while using MongoDB
spring.batch.jdbc.initialize-schema=never

spring.main.allow-bean-definition-overriding=true
# 2. Disable JPA/Hibernate auto-configuration 
# (Since you are using MongoDB, you don't need Hibernate trying to scan for entities)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

#To see loggers in consol
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


# To expose only specific endpoints (recommended)
#management.endpoints.web.exposure.include=health,info,metrics,env,beans,trace

# OR to expose ALL endpoints (use only in development)
management.endpoints.web.exposure.include=*