resilience4j:
  circuitbreaker:
    instances:
      redisService:
        registerHealthIndicator: true
        slidingWindowSize: 2          # Check the last 10 calls
        failureRateThreshold: 20       # If 50% fail, open the circuit
        waitDurationInOpenState: 5s   # Wait 30s before trying Redis again
        permittedNumberOfCallsInHalfOpenState: 1